### ISSUE TITLE
Create Student Registration Form for each event

### ISSUE THREAD

**Issue by SAMAHANSysDev** [SAMAHAN-Systems-Development/ACMS-frontend-2023#1]
**Page:**

![Image](https://github.com/SAMAHAN-Systems-Development/ACMS-frontend-2023/assets/59654805/ce7ca1fe-3afa-4723-aa9e-66c4562b1f7a)

Figma Link: https://www.figma.com/file/FdXMgSD23NCTBgw4eCOaYK/ACMS-UI%2FUX-w-Domi-%26-Shika?type=design&node-id=15%3A32&mode=design&t=1dn6i4x4n8hiKkGd-1

**Requirements:**

- [x] Finished creating the UI
- [x] The frontend endpoint should be '/events/register/{form-name}'
- [x] Every field is required to be filled by the student
- [x] The payment field will only show up if the event requires payment
- [x] Will directly upload the photo to supabase storage
- [x] Will send a request to the backend endpoint which is '/student/submit-registration'

**Comment by viverbungag** [comment]
Sorry, just changed the endpoint for easier verification in auth.
