### ISSUE TITLE
Create view event page

### ISSUE THREAD

**Issue by SAMAHANSysDev** [SAMAHAN-Systems-Development/ACMS-frontend-2023#13]
**Page:**

![Image](https://github.com/SAMAHAN-Systems-Development/ACMS-frontend-2023/assets/59654805/5d3f5555-d3c2-4be6-a4a1-2ee3516df7c1)

Figma Link: https://www.figma.com/file/FdXMgSD23NCTBgw4eCOaYK/ACMS-UI%2FUX-w-Domi-%26-Shika?type=design&node-id=15%3A32&mode=design&t=1dn6i4x4n8hiKkGd-1

**Requirements:**

- [x] Finished creating the UI
- [x] Correct information of the events
- [x] Clicking the 'View Form' button will redirect to its respective form page '/events/{form-name}/register'
- [x] Clicking the 'View Accepted Payments' button will open this modal: https://github.com/orgs/SAMAHAN-Systems-Development/projects/7?pane=issue&itemId=47763656
- [x] Clicking the 'View Declined Payments' button will open this modal: https://github.com/orgs/SAMAHAN-Systems-Development/projects/7?pane=issue&itemId=47763658
- [x] The search bar searches the student name
- [x] Clicking the 'View' button on the table of the registered students will open this page (/student/{uuid}): https://github.com/orgs/SAMAHAN-Systems-Development/projects/7?pane=issue&itemId=47763659

**Comment by doblitro** [comment]
Final UI

![Image](https://github.com/SAMAHAN-Systems-Development/ACMS-frontend-2023/assets/57930589/845abec3-0d8e-4dd6-86db-325f48bbab77)
